# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'Alamofire', '~> 4.7'
pod 'Curry'
pod 'Runes'

target 'KeioClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KeioClient

  target 'KeioClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KeioClientUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
